angular
	.module("myApp.products")
	.service("productsService", function(){
			this.getAll = function(){
				return [
					{id : 1, name : "Pen", cost : 5, units : 100, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid cupiditate, inventore, dolorem est dignissimos aut repellat quibusdam maxime sit quaerat. Dignissimos incidunt laborum numquam illo reiciendis sapiente officiis voluptatum vel!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolor delectus, commodi tenetur, nostrum odio exercitationem nulla eum facilis numquam culpa, distinctio accusantium esse! Vitae incidunt deserunt voluptatem reprehenderit corporis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis delectus doloremque perferendis magni est in obcaecati quam, vel debitis dolore a odio ipsam velit sit nihil earum. Recusandae, perspiciatis, quae?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi debitis suscipit, beatae dolore perferendis architecto cumque cum molestias asperiores maiores temporibus eos, est explicabo perspiciatis officia natus laboriosam obcaecati soluta."},
					{id : 2, name : "Hen", cost : 100, units : 20, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid cupiditate, inventore, dolorem est dignissimos aut repellat quibusdam maxime sit quaerat. Dignissimos incidunt laborum numquam illo reiciendis sapiente officiis voluptatum vel!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolor delectus, commodi tenetur, nostrum odio exercitationem nulla eum facilis numquam culpa, distinctio accusantium esse! Vitae incidunt deserunt voluptatem reprehenderit corporis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis delectus doloremque perferendis magni est in obcaecati quam, vel debitis dolore a odio ipsam velit sit nihil earum. Recusandae, perspiciatis, quae?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi debitis suscipit, beatae dolore perferendis architecto cumque cum molestias asperiores maiores temporibus eos, est explicabo perspiciatis officia natus laboriosam obcaecati soluta."},
					{id : 3, name : "Den", cost : 500, units : 5, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid cupiditate, inventore, dolorem est dignissimos aut repellat quibusdam maxime sit quaerat. Dignissimos incidunt laborum numquam illo reiciendis sapiente officiis voluptatum vel!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolor delectus, commodi tenetur, nostrum odio exercitationem nulla eum facilis numquam culpa, distinctio accusantium esse! Vitae incidunt deserunt voluptatem reprehenderit corporis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis delectus doloremque perferendis magni est in obcaecati quam, vel debitis dolore a odio ipsam velit sit nihil earum. Recusandae, perspiciatis, quae?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi debitis suscipit, beatae dolore perferendis architecto cumque cum molestias asperiores maiores temporibus eos, est explicabo perspiciatis officia natus laboriosam obcaecati soluta."},
					{id : 4, name : "Ten", cost : 10, units : 10, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid cupiditate, inventore, dolorem est dignissimos aut repellat quibusdam maxime sit quaerat. Dignissimos incidunt laborum numquam illo reiciendis sapiente officiis voluptatum vel!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolor delectus, commodi tenetur, nostrum odio exercitationem nulla eum facilis numquam culpa, distinctio accusantium esse! Vitae incidunt deserunt voluptatem reprehenderit corporis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis delectus doloremque perferendis magni est in obcaecati quam, vel debitis dolore a odio ipsam velit sit nihil earum. Recusandae, perspiciatis, quae?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi debitis suscipit, beatae dolore perferendis architecto cumque cum molestias asperiores maiores temporibus eos, est explicabo perspiciatis officia natus laboriosam obcaecati soluta."}
				]
			};
		});